import type { FeedSource } from "./types";

export const SOURCES: FeedSource[] = [
  {
    name: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/rssindex",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 62,
    sourceType: "media",
  },
  {
    name: "CNBC Markets",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 70,
    sourceType: "media",
  },
  {
    name: "WSJ Markets",
    url: "https://feeds.content.dowjones.io/public/rss/RSSMarketsMain",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 86,
    sourceType: "media",
    articleHosts: ["www.wsj.com", "wsj.com"],
  },
  {
    name: "WSJ Markets Legacy",
    url: "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 84,
    sourceType: "media",
    articleHosts: ["www.wsj.com", "wsj.com"],
  },
  {
    name: "Federal Reserve",
    url: "https://www.federalreserve.gov/feeds/press_all.xml",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 100,
    sourceType: "official",
  },
  {
    name: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 96,
    sourceType: "official",
  },
  {
    name: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    category: "ai",
    enabledByDefault: true,
    priority: 90,
    sourceType: "official",
  },
  {
    name: "Google DeepMind",
    url: "https://deepmind.google/blog/rss.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 94,
    sourceType: "official",
  },
  {
    name: "MIT AI News",
    url: "https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 78,
    sourceType: "research",
  },
  {
    name: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 72,
    sourceType: "research",
  },
  {
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    category: "ai",
    enabledByDefault: true,
    priority: 60,
    sourceType: "media",
  },
  {
    name: "Techmeme",
    url: "https://www.techmeme.com/feed.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 84,
    sourceType: "media",
  },
  {
    name: "SiliconANGLE",
    url: "https://siliconangle.com/feed/",
    category: "ai",
    enabledByDefault: true,
    priority: 78,
    sourceType: "media",
  },
  {
    name: "DataCenterDynamics",
    url: "https://www.datacenterdynamics.com/en/rss/",
    category: "ai",
    enabledByDefault: true,
    priority: 76,
    sourceType: "media",
  },
  {
    name: "Semiconductor Engineering",
    url: "https://semiengineering.com/feed/",
    category: "ai",
    enabledByDefault: true,
    priority: 80,
    sourceType: "research",
  },
];
