import type { Category, FeedSource } from "./types";

export const CATEGORY_ORDER: Category[] = [
  "crypto",
  "us_stocks_macro",
  "ai",
  "taiwan_stocks",
];

export const SOURCES: FeedSource[] = [
  {
    name: "CoinDesk",
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/?outputType=xml",
    category: "crypto",
    enabledByDefault: true,
    priority: 70,
    sourceType: "media",
  },
  {
    name: "Cointelegraph",
    url: "https://cointelegraph.com/rss",
    category: "crypto",
    enabledByDefault: true,
    priority: 60,
    sourceType: "media",
  },
  {
    name: "Decrypt",
    url: "https://decrypt.co/feed",
    category: "crypto",
    enabledByDefault: true,
    priority: 68,
    sourceType: "media",
  },
  {
    name: "The Defiant",
    url: "https://thedefiant.io/feed/",
    category: "crypto",
    enabledByDefault: true,
    priority: 64,
    sourceType: "media",
  },
  {
    name: "CFTC General Press Releases",
    url: "https://www.cftc.gov/RSS/RSSGP/rssgp.xml",
    category: "crypto",
    enabledByDefault: true,
    priority: 95,
    sourceType: "official",
  },
  {
    name: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/rssindex",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 62,
    sourceType: "media",
  },
  {
    name: "CNBC Markets",
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 70,
    sourceType: "media",
  },
  {
    name: "Federal Reserve",
    url: "https://www.federalreserve.gov/feeds/press_all.xml",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 100,
    sourceType: "official",
  },
  {
    name: "Bank of England News",
    url: "https://www.bankofengland.co.uk/rss/news",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 48,
    sourceType: "official",
  },
  {
    name: "Nasdaq AAPL",
    url: "https://www.nasdaq.com/feed/rssoutbound?symbol=AAPL",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 76,
    sourceType: "media",
  },
  {
    name: "Nasdaq MSFT",
    url: "https://www.nasdaq.com/feed/rssoutbound?symbol=MSFT",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 76,
    sourceType: "media",
  },
  {
    name: "Nasdaq GOOGL",
    url: "https://www.nasdaq.com/feed/rssoutbound?symbol=GOOGL",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 76,
    sourceType: "media",
  },
  {
    name: "Nasdaq NVDA",
    url: "https://www.nasdaq.com/feed/rssoutbound?symbol=NVDA",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 76,
    sourceType: "media",
  },
  {
    name: "Nasdaq INTC",
    url: "https://www.nasdaq.com/feed/rssoutbound?symbol=INTC",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 76,
    sourceType: "media",
  },
  {
    name: "Nasdaq NOK",
    url: "https://www.nasdaq.com/feed/rssoutbound?symbol=NOK",
    category: "us_stocks_macro",
    enabledByDefault: true,
    priority: 72,
    sourceType: "media",
  },
  {
    name: "MIT AI News",
    url: "https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 78,
    sourceType: "research",
  },
  {
    name: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 72,
    sourceType: "research",
  },
  {
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai/feed/",
    category: "ai",
    enabledByDefault: true,
    priority: 60,
    sourceType: "media",
  },
  {
    name: "OpenAI News",
    url: "https://openai.com/news/rss.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 96,
    sourceType: "official",
  },
  {
    name: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    category: "ai",
    enabledByDefault: true,
    priority: 90,
    sourceType: "official",
  },
  {
    name: "Google DeepMind",
    url: "https://deepmind.google/blog/rss.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 94,
    sourceType: "official",
  },
  {
    name: "BAIR Blog",
    url: "https://bair.berkeley.edu/blog/feed.xml",
    category: "ai",
    enabledByDefault: true,
    priority: 80,
    sourceType: "research",
  },
  {
    name: "iThome News",
    url: "https://www.ithome.com.tw/rss",
    category: "ai",
    enabledByDefault: true,
    priority: 66,
    sourceType: "media",
    articleHosts: ["www.ithome.com.tw", "ithome.com.tw"],
  },
  {
    name: "FSC Press Releases",
    url: "https://www.fsc.gov.tw/RSS/Messages?serno=201202290016&language=english",
    category: "taiwan_stocks",
    enabledByDefault: false,
    priority: 96,
    sourceType: "official",
  },
  {
    name: "TWSE News",
    url: "https://www.twse.com.tw/rwd/zh/news/feed?type=rss",
    category: "taiwan_stocks",
    enabledByDefault: false,
    priority: 94,
    sourceType: "official",
  },
  {
    name: "CNA Finance",
    url: "https://feeds.feedburner.com/rsscna/finance",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 74,
    sourceType: "media",
    articleHosts: ["www.cna.com.tw", "cna.com.tw"],
  },
  {
    name: "CNA Technology",
    url: "https://feeds.feedburner.com/rsscna/technology",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 70,
    sourceType: "media",
    articleHosts: ["www.cna.com.tw", "cna.com.tw"],
  },
  {
    name: "MoneyDJ Finance News",
    url: "https://www.moneydj.com/kmdj/RssCenter.aspx?svc=NW&fno=1&arg=X0000000",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 68,
    sourceType: "media",
    articleHosts: ["www.moneydj.com", "moneydj.com"],
  },
  {
    name: "DIGITIMES Daily",
    url: "https://www.digitimes.com/rss/daily.xml",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 72,
    sourceType: "media",
    articleHosts: ["www.digitimes.com", "digitimes.com"],
  },
  {
    name: "TechNews Finance",
    url: "https://finance.technews.tw/feed/",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 68,
    sourceType: "media",
    articleHosts: ["finance.technews.tw", "technews.tw"],
  },
  {
    name: "Business Weekly Investment",
    url: "https://www.businessweekly.com.tw/Event/feedsec.aspx?feedid=10&channelid=15",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 58,
    sourceType: "media",
    articleHosts: ["www.businessweekly.com.tw", "businessweekly.com.tw"],
  },
  {
    name: "MOPS Material Information 201001",
    url: "https://mopsov.twse.com.tw/nas/rss/mopsrss201001.xml",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 98,
    sourceType: "official",
    fetchMode: "rss-big5",
  },
  {
    name: "MOPS Material Information 201002",
    url: "https://mopsov.twse.com.tw/nas/rss/mopsrss201002.xml",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 98,
    sourceType: "official",
    fetchMode: "rss-big5",
  },
  {
    name: "MOPS Material Information 201003",
    url: "https://mopsov.twse.com.tw/nas/rss/mopsrss201003.xml",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 98,
    sourceType: "official",
    fetchMode: "rss-big5",
  },
  {
    name: "Yahoo Taiwan Stock News",
    url: "https://tw.stock.yahoo.com/rss?category=tw-market",
    category: "taiwan_stocks",
    enabledByDefault: false,
    priority: 56,
    sourceType: "media",
    articleHosts: ["tw.stock.yahoo.com", "tw.news.yahoo.com"],
  },
  {
    name: "Yahoo Taiwan Stock News Feed",
    url: "https://tw.stock.yahoo.com/rss?category=news",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 62,
    sourceType: "media",
    articleHosts: ["tw.stock.yahoo.com", "tw.news.yahoo.com"],
  },
  {
    name: "Yahoo Taiwan Stock Research",
    url: "https://tw.stock.yahoo.com/rss?category=research",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 60,
    sourceType: "research",
    articleHosts: ["tw.stock.yahoo.com", "tw.news.yahoo.com"],
  },
  {
    name: "Yahoo Taiwan Funds News",
    url: "https://tw.stock.yahoo.com/rss?category=funds-news",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 58,
    sourceType: "media",
    articleHosts: ["tw.stock.yahoo.com", "tw.news.yahoo.com"],
  },
  {
    name: "Cnyes Taiwan Stock News",
    url: "https://news.cnyes.com/news/cat/tw_stock_news",
    category: "taiwan_stocks",
    enabledByDefault: false,
    priority: 58,
    sourceType: "media",
    fetchMode: "html",
    parser: "cnyes_tw_stock_html",
    articleHosts: ["news.cnyes.com", "cnyes.com"],
  },
  {
    name: "UDN Taiwan Stock News",
    url: "https://money.udn.com/money/cate/5594",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 60,
    sourceType: "media",
    fetchMode: "html",
    parser: "udn_tw_stock_html",
    articleHosts: ["money.udn.com", "udn.com"],
  },
  {
    name: "UDN Taiwan Industry News",
    url: "https://money.udn.com/money/cate/5591",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 66,
    sourceType: "media",
    fetchMode: "html",
    parser: "udn_jsonld_list",
    articleHosts: ["money.udn.com", "udn.com"],
  },
  {
    name: "TPEx Press Releases",
    url: "https://www.tpex.org.tw/www/zh-tw/news/list",
    category: "taiwan_stocks",
    enabledByDefault: true,
    priority: 92,
    sourceType: "official",
    fetchMode: "api-json",
    parser: "tpex_press_json",
    articleHosts: ["www.tpex.org.tw", "tpex.org.tw"],
  },
];

export function getSourcesByCategory(includeTaiwan: boolean): Record<Category, FeedSource[]> {
  return {
    crypto: SOURCES.filter((source) => source.category === "crypto"),
    us_stocks_macro: SOURCES.filter(
      (source) => source.category === "us_stocks_macro",
    ),
    ai: SOURCES.filter((source) => source.category === "ai"),
    taiwan_stocks: includeTaiwan
      ? SOURCES.filter((source) => source.category === "taiwan_stocks")
      : [],
  };
}
